src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=AuteurRepository::class)
 * @UniqueEntity("nom_prenom" , message="Le nom de ce auteur existe déjà !! ")

 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Le nom ne doit pas être vide !")
     * @Assert\Length(min=2,max=100, 
     *         minMessage="Le nom de l'acteur doit faire au moins {{ limit }} caractère !", 
     *         maxMessage="Le nom ne doit pas dépasser {{ limit }} caractères !")
     * 
     * @Assert\Regex("/^[a-zA-Z ]+$/", message=" le nom ne doit pas contenir des chiffre ou caracère spéciaux")
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="boolean")
     * 
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     * @Assert\LessThan("today",message ="Vous devez choisir une date inférieure à la date d'aujourd'huit")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Selectionnez la nationnalité de l'auteur !")
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, inversedBy="auteurs")
     */
    private $ecrire;

    public function __construct()
    {
        $this->ecrire = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?bool
    {
        return $this->sexe;
    }

    public function setSexe(bool $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getEcrire(): Collection
    {
        return $this->ecrire;
    }

    public function addEcrire(Livre $ecrire): self
    {
        if (!$this->ecrire->contains($ecrire)) {
            $this->ecrire[] = $ecrire;
        }

        return $this;
    }

    public function removeEcrire(Livre $ecrire): self
    {
        $this->ecrire->removeElement($ecrire);

        return $this;
    }

    public function __toString(): string
    {
        return $this->nom_prenom;
    }

    public function getNbecrits()
    {
        // Récrupérer la collections de livres 
        $mesLivres = $this->getEcrire() ; 
        $nbLivres = sizeof($mesLivres) ; 
        return $nbLivres ; 
    }
    
}

src/Entity/Genre.php
<?php

namespace App\Entity;

use App\Repository\GenreRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert ; 
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GenreRepository::class)
 * @UniqueEntity("nom" , message="Ce nom existe deja !")
 */
class Genre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom ne doit pas être vide !")
     * @Assert\Regex("/^[a-zA-Z ]+$/", message=" le nom ne doit pas contenir des chiffre caracère spéciaux")
     * 
     */
    private $nom;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, inversedBy="genres")
     *
     * 
     */
    private $Appartenir;

    public function __construct()
    {
        $this->Appartenir = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getAppartenir(): Collection
    {
        return $this->Appartenir;
    }

    public function addAppartenir(Livre $appartenir): self
    {
        if (!$this->Appartenir->contains($appartenir)) {
            $this->Appartenir[] = $appartenir;
        }

        return $this;
    }

    public function removeAppartenir(Livre $appartenir): self
    {
        $this->Appartenir->removeElement($appartenir);

        return $this;
    }

    public function __toString(): string
    {
        return $this->nom;
    }
    
    public function getNbpages()
    {
        // Récupérer les livres concernés
        $mesLivres = $this->getAppartenir() ; 
        
        //Calculer le nombre de pages total 
        $nbPagesTot = 0 ; 
        foreach($mesLivres as $livre){
            $nbPagesTot += $livre->getNbpages() ; 
        }

        return $nbPagesTot ; 
    }

    public function getNbpagesmoy()
    {
        // Récupérer les livres concernés 
        $mesLivres = $this->getAppartenir() ; 

        // Calculer la moyenne des pages pour chaque livres
        $somme = 0 ; 
        $nbLivre = 0 ; 
        
        foreach($mesLivres as $livre){
            $somme += $livre->getNbpages() ; 
            $nbLivre++ ; 
        }

        
        if($nbLivre != 0){
            $moyenne = $somme/$nbLivre ; 
            return (int)$moyenne ; 
        }
        else
            return null ; 
    }
    
    public function getAuteurs(){

        // Récupérer les livres 
        $livres = $this->getAppartenir() ; 
        $tab = array() ; 

        foreach($livres as $livre){
            // Récupérer les auteurs
            $auteurs = $livre->getAuteurs() ; 
            foreach($auteurs as $auteur){
                array_push($tab, $auteur) ; 
            }
        }

        //Trier le tableau 



        return array_unique($tab) ; 

    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 * @UniqueEntity("isbn" , message="ce isbn existe déjà !! ")
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\Isbn(
     *     type = "isbn13",
     *     message = "ce Isbn n'est pas correcte."
     * )
     * 
     * @Assert\NotBlank(message="Selectionnez l'isbn d'un livre !")
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Selectionnez le nombre de page !")
     * @Assert\Regex("/^[0-9]+$/", message="Vous n'avez pas utilisé le format correct")
     */
    private $nbpages;

    /**
     * @ORM\Column(type="date")
     * @Assert\LessThan("today", message ="Vous devez choisir une date inférieure à la date d'aujourd'hui")
     */
    private $date_de_parution;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * 
     * @Assert\LessThanOrEqual(20, message="La note doit être inférieur a 20")  
     * @Assert\GreaterThanOrEqual(0, message="La note doit être supérieur a 0 ") 
     * @Assert\Regex("/^[0-9]$/", message= "vous devez siasir le bon format")
     * 
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Auteur::class, mappedBy="ecrire")
     */
    private $auteurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, mappedBy="Appartenir")
     */
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNbpages(): ?int
    {
        return $this->nbpages;
    }

    public function setNbpages(int $nbpages): self
    {
        $this->nbpages = $nbpages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
            $auteur->addEcrire($this);
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        if ($this->auteurs->removeElement($auteur)) {
            $auteur->removeEcrire($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
            $genre->addAppartenir($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeAppartenir($this);
        }

        return $this;
    }

    public function getAuteurgenres(){

        $tab  = array();

        $genres = $this->getGenres();

        $tab[0] = $genres[0]->getNom();
       // dd($genres[1]->getNom());
        for ($i=1; $i<$genres->count(); $i++) { 

            if(in_array($genres[$i]->getNom(), $tab))
            {
               echo('NON');

                array_push($tab,$genres[$i]->getNom());
            }
            else{

            }

        }

        return $tab;

    }
    
}

src/Form/AuteurType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use Doctrine\Common\Collections\Expr\Value;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Intl\Intl;

class AuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $countries = Intl::getRegionBundle()->getCountryNames();

        $builder
            ->add('nom_prenom',TextType::class)
            ->add('sexe',ChoiceType::class,['choices'  => [
                'Homme' => true,
                'Femme' => false,
            ]],)
            ->add('date_de_naissance', DateType::class, [
                'placeholder'=>'Date de naissance',
                // renders it as a single text box
                'widget' => 'single_text',
            ])
            ->add('nationalite',ChoiceType::class,[
                'choices' => array_flip($countries),
                'placeholder' => 'Selectionner votre pays',
                'preferred_choices' => array('FR'),
                
            ])
            ->add('submit',SubmitType::class,array('label'=>'Ajouter Auteur'))
 
            // ->add('ecrire',TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Auteur::class,
        ]);
    }
}

templates/auteur/ajouter.html.twig
{% extends "base.html.twig" %}
    {% block contenu %}
    {{ form_start(monFormulaire) }}
        <div class="container">
            <h3 class='text-center text-warning '>
                <a href='{{ path('lister_auteurs') }}' class="btn btn-success" style="display: block; margin-left: auto; margin-right: auto; width: 7%; border-radius: 25px; position: relative; float: left;">
                    <img src="/assets/img/precedent.png" alt="Modifier" style="width:20px"/>
                </a>
                <br>
            Ajouter un auteur</h3>
            <form>
                <div class="form-group">
                    <label for="nomprenom" class='mt-3 mb-2'>{{form_label(monFormulaire.nom_prenom , "Nom et prénom")}} : </label>
                    {{form_widget(monFormulaire.nom_prenom,{'attr': {'class': 'form-control mb-2'}})}}
                    {{ form_errors(monFormulaire.nom_prenom) }}

                </div>
                <div class="form-group" class='mt-3 mb-2'>
                    <label for="exampleInputPassword1" class="mt-3 mb-2">{{form_label(monFormulaire.nationalite, "Nationalité")}} :</label>
                    {{form_widget(monFormulaire.nationalite,{'attr': {'class': 'form-control mb-2'}})}}
                    {{ form_errors(monFormulaire.nationalite) }}

                </div>
                <div class="form-group" class='my-3'>
                    <label for="exampleInputPassword1" class= "mt-3 mb-2">{{form_label(monFormulaire.sexe, "Sexe")}} :</label>
                    {{form_widget(monFormulaire.sexe,{'attr': {'class': 'form-control mb-2'}})}}
                    {# <input type="password" class="form-control" id="exampleInputPassword1"> #}
                </div>
                <div class="form-group datepicker">
                    <label for="exampleInputPassword1" class='mt-3 mb-2'>{{form_label(monFormulaire.date_de_naissance)}} :</label>
                    {{form_widget(monFormulaire.date_de_naissance,{'attr': {'class': 'form-control mb-5'}})}}
                    {{ form_errors(monFormulaire.date_de_naissance) }}
                </div>
                <div class="mt-3 text-center">
                                {{form_widget(monFormulaire.submit)}}

                </div>
                
                <div class="form-group">
            </form>
            
            {{ form_end(monFormulaire) }}
            <script>
            $(document).on('ready', function() {
                    $('.js-datepicker').datepicker({
                        format: 'dd-mm-yyyy',
                    });
                });

            </script>
    {% endblock %}

templates/auteur/augmenter.html.twig
{% extends "base.html.twig" %}
    {% block contenu %}
    {{ form_start(form) }}
    {{ form_row(form._token) }}

        <div class="container">
        <h3 class="text-center mt-0">
                <a href='{{ path('lister_auteurs') }}' class="btn btn-success" style="display: block; margin-left: auto; margin-right: auto; width: 7%; border-radius: 25px; position: relative; float: left;">
                    <img src="/assets/img/precedent.png" alt="Modifier" style="width:20px"/>
                </a>
                <br>
        Ajouter une note : </h3>
	    <hr class="divider"/>            
        <h3 class="mb-4">Auteur : <span class="text-primary"> {{auteur.nomprenom}} </span></h3>
        <h5>Listes des livres : </h5>
        <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Isbn</th>
            <th scope="col">Titre</th>
            <th scope="col">Note</th>
            </tr>
        </thead>
        <tbody>
         {% for livre in auteur.ecrire %}
            <tr>
            <th scope="row">{{livre.id}}</th>
            <td>{{livre.isbn}}</td>
            <td>{{livre.titre}}</td>
            <td>{{livre.note}}</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
           
            
             {% for message in app.flashes('success') %}
					<div class="alert alert-success alert-dismissible fade show">
						<strong>{{message}}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

					</div>
            {% endfor %}
            {% for message in app.flashes('error') %}
					<div class="alert alert-danger alert-dismissible fade show">
						<strong>{{message}}</strong> 
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

					</div>
            {% endfor %}
            <form>
                <div class="form-group">
                    <label for="nomprenom" class='my-3'>{{form_label(form.note)}} : </label>
                    {{form_widget(form.note,{'attr': {'class': 'form-control'}})}}
                </div>
               
                
                {{form_widget(form.submit,{"attr":{'class':' btn btn-primary text-center my-3'}})}}
                
                <div class="form-group">
            </form>
          

  
    {% endblock %}
    

templates/auteur/auteurGenre.html.twig
{% extends "base.html.twig" %}
{% block contenu %}
    <div class="card-columns">
        <h1 class='text-center mb-5'>
        <a href='{{ path('lister_auteurs') }}' class="btn btn-success" style="display: block; margin-left: auto; margin-right: auto; width: 7%; border-radius: 25px; position: relative; float: left;">
                    <img src="/assets/img/precedent.png" alt="Modifier" style="width:20px"/>
                </a>
                <br>
        List des genres pour l'auteur : <span class='text-primary'>{{auteur.nomprenom}}</span></h1>
        <div class="card justify-content-center border-5">
            <img class="card-img-top" src="holder.js/100x180/" alt="">
            <div class="card-body">
                {% for genre in genres %}  
                    <ul>
                        <li>{{genre.nom}}  </li>
                    </ul> 
                     
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/auteur/auteursGenres.html.twig
{% extends "base.html.twig" %}
{% block contenu %}
    <div class="card-columns">
<h3 class="text-center mt-0">
                <a href='{{ path('lister_auteurs') }}' class="btn btn-success" style="display: block; margin-left: auto; margin-right: auto; width: 7%; border-radius: 25px; position: relative; float: left;">
                    <img src="/assets/img/precedent.png" alt="Modifier" style="width:20px"/>
                </a>
            <br>
	Liste des genres par auteurs en fonction de la date de parution des livres :</h3>
	<hr class="divider"/>
	<table class="table">
			<thead>
				<tr>
					<th scope="col"></th>
				</tr>
			</thead>
			<tbody>
				{% for auteur in auteurs %}
					<tr>
						<td>{{auteur.nomprenom}}</td>
					</tr>
					<td>
					{% for livre in auteur.ecrire %}
						{% for genre in livre.auteurgenres %}
							<ul>
								<li>{{livre.titre}} &#x2192 {{ genre }}</li>
							</ul>
						{% endfor %}
					{% endfor %}
					</td>
				{% endfor %}
			</tbody>
			</table>
        {# <table class="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Auteur</th>
					<th scope="col">Liste des genres</th>
					<th scope="col">Nombre de livres écrits</th>
					<th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for auteur in auteurs %}
					<tr>
						<th scope="row">{{ auteur.id }}</th>
						<td>{{ auteur.nomPrenom }}</td>
						<td>
							{% for item in test %}
								{{ item.nom_prenom }}
							{% endfor %}
						<td>
						<td>{{ auteur.nbecrits }}</td>
						<td>
							<a href="" class="btn btn-danger">
								<img src="/assets/img/corbeille.png" alt="Supprimer" style="width:20px"/>
							</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table> #}
    </div>
{% endblock %}

templates/auteur/detail.html.twig
{% extends "base.html.twig" %}
{% block contenu %}

       <div style="box-shadow: 2px 5px 3px 2px  #F4623A " class="card border  border-5 rounded-bottom " >
            <div class="card-header " style="background-color:#F4623A">
                <h3 class="text-center font-weight-bold font-italic pt-2 mt-2">
                <a href='{{ path('lister_auteurs') }}' class="btn btn-success" style="display: block; margin-left: auto; margin-right: auto; width: 7%; border-radius: 25px; position: relative; float: left;">
                    <img src="/assets/img/precedent.png" alt="Modifier" style="width:20px"/>
                </a>
                <br>
                 Information d'auteur</h3>
            </div>
            <div class="card-body">

                <table class="table bg-ligh table-striped text-center"> 
                    <tbody>
                    <tr>
                        <th scope="row">Nom et prénom</th>
                        <td>{{auteur.nomprenom}}</td>
                    </tr>    
                    <tr>
                        <th scope="row">Nationnalité</th>
                        <td>{{auteur.nationalite}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Sexe</th>
                        <td>{{auteur.sexe ? 'Homme': 'Femme'}}</td>
                    </tr> 
                    <tr>
                        <th scope="row">Date de naissance</th>
                        <td>{{auteur.datedenaissance|date('d/m/Y')}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Listes des livres</th>
                        <td>
                             {% for ecrire in ecrires %}
                               <p class="card-text">{{ecrire.titre}} <span><a href='{{ path ("afficher_livre",{'id':ecrire.id})}}'>voir</a></span></p>
                              {% else %}
                                <p class='text-primary'>Ce auteur n'aucun livre</p>
                             {% endfor %}
                            
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Listes des genres</th>
                        <td>
                             {% for ecrire in ecrires %}
                                {% for genre in ecrire.genres %}

                                    {{genre}}<br>
                                {% else %}
                                     <p class='text-primary'>Ce auteur n'aucun livre</p>
                                {% endfor %}
                             {% endfor %}
                            
                        </td>
                    </tr>
                   
                    
                    
                    </tbody>
                </table>
             </div>
        </div> 
 
{% endblock %}

templates/auteur/listerAuteurs.html.twig
{# {% extends "base.html.twig" %}
{% block contenu %}
    <div class="card-columns">
        <div class="card justify-content-center border-5">
            <img class="card-img-top" src="holder.js/100x180/" alt="">
            <div class="card-body">
                {% for list in lists %}
                                    <p class="card-text">{{list.nomprenom}}</p>
                                    {% for ecrire in list.ecrire %}
                                        <ul>
                                            <li>{{ecrire.titre}}</li>
                                        </ul>
                                        
                                    {% endfor %}

                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %} #}

{% extends "base.html.twig" %}
    {% block contenu %}

       	<div id="portfolio">
         {# <h3 class='text-center text-warning'>Liste des auteurs ayant au mois 3 livres</h3> #}
         <h3 class="text-center mt-0">
         <a href='{{ path('lister_auteurs') }}' class="btn btn-success" style="display: block; margin-left: auto; margin-right: auto; width: 7%; border-radius: 25px; position: relative; float: left;">
                    <img src="/assets/img/precedent.png" alt="Modifier" style="width:20px"/>
                </a>
                <br>
         Liste des auteurs ayant au mois 3 livres</h3>
	     <hr class="divider"/>
		<table class="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Auteur</th>
                    <th scope="col">Livres</th>
				</tr>
			</thead>
			<tbody>
				{% for list in lists %}
					<tr>
						<th scope="row">{{ list.id }}</th>
						<td>{{ list.nomprenom }}</td>
						<td>{% for ecrire in list.ecrire %}
                            {{ ecrire.titre }}<br>   
                        {% endfor %}</td> 
					</tr>
				{% endfor %}
			</tbody>
		</table>
        
	</div>
{% endblock %}

templates/auteur/listlivresupprimer.html.twig
{% extends "base.html.twig" %}
    {% block contenu %}

       	<div id="portfolio">
         <h3 class='text-center text-warning'>Liste des livres : {{auteur.nomprenom}}</h3>
         
		<table class="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">isbn</th>
					<th scope="col">titre</th>
					<th scope="col">Nombre de pages</th>
					{# <th scope="col">Date de parution</th> #}
                    <th scope="col">Note</th>
				</tr>
			</thead>
			<tbody>
				{% for livre in auteur.ecrire %}
					<tr>
						<th scope="row">{{ livre.id }}</th>
						<td>{{ livre.isbn }}</td>
						<td>{{ livre.titre }}</td>
                        <td>{{ livre.nbpages }}</td>
						{# <td>{{ livre.datedeparution }}</td> #}
                        <td>{{ livre.note }}</td>
						
					</tr>
				{% endfor %}
			</tbody>
		</table>
        <a data-bs-toggle="modal" data-bs-target="#id" class="btn btn-danger">
            Supprimer l'auteur
        </a>
        <div class="modal fade" id="id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Supprimer : <span class='text-primary'> {{auteur.nomprenom}}</span></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p class='text-danger'>Attention en cliquant sur supprimer, vous supprimez l'auteur et tous les livres de ce auteur</p>                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                    <a href='{{path ('supprimer_auteur_livre',{'id':auteur.id})}}' type="button" class="btn btn-danger">Supprimer</a>
                </div>
                </div>
            </div>
        </div>    
	</div>
           
            
            
          

  
    {% endblock %}
    